import {
  Activity,
  Atom,
  Award,
  BookOpen,
  Bot,
  BrainCircuit,
  BriefcaseBusiness,
  Building2,
  ChartColumn,
  ClipboardCheck,
  Cloud,
  CloudCheck,
  CloudCog,
  CloudUpload,
  CodeXml,
  Cpu,
  Database,
  FileSearch,
  FlaskConical,
  Gauge,
  GraduationCap,
  Infinity as InfinityIcon,
  Layers,
  LayoutGrid,
  Lock,
  MessagesSquare,
  MonitorCheck,
  MousePointerClick,
  PenTool,
  Presentation,
  Puzzle,
  Radar,
  RefreshCw,
  Repeat,
  Rocket,
  Search,
  Shield,
  ShieldCheck,
  ShieldHalf,
  Siren,
  SlidersHorizontal,
  SquareKanban,
  Target,
  TrendingUp,
  UserCheck,
  Users,
  Waypoints,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Icons that content files may reference by key. Keeping content data-only (no component
 * imports) means copy can be edited without touching React code.
 */
export const icons = {
  activity: Activity,
  atom: Atom,
  award: Award,
  "book-open": BookOpen,
  bot: Bot,
  brain: BrainCircuit,
  briefcase: BriefcaseBusiness,
  building: Building2,
  chart: ChartColumn,
  "clipboard-check": ClipboardCheck,
  cloud: Cloud,
  "cloud-check": CloudCheck,
  "cloud-cog": CloudCog,
  "cloud-upload": CloudUpload,
  code: CodeXml,
  cpu: Cpu,
  database: Database,
  "file-search": FileSearch,
  flask: FlaskConical,
  gauge: Gauge,
  "graduation-cap": GraduationCap,
  infinity: InfinityIcon,
  layers: Layers,
  "layout-grid": LayoutGrid,
  lock: Lock,
  messages: MessagesSquare,
  "monitor-check": MonitorCheck,
  pointer: MousePointerClick,
  "pen-tool": PenTool,
  presentation: Presentation,
  puzzle: Puzzle,
  radar: Radar,
  refresh: RefreshCw,
  repeat: Repeat,
  rocket: Rocket,
  search: Search,
  shield: Shield,
  "shield-check": ShieldCheck,
  "shield-half": ShieldHalf,
  siren: Siren,
  sliders: SlidersHorizontal,
  kanban: SquareKanban,
  target: Target,
  "trending-up": TrendingUp,
  "user-check": UserCheck,
  users: Users,
  waypoints: Waypoints,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;
