/**
 * Scans public/images for files matching the slots in lib/images.ts and writes
 * lib/image-manifest.json (intrinsic size + tiny blur placeholder per slot).
 * Also regenerates docs/IMAGE_BRIEF.md so the brief always matches the registry.
 *
 * Runs automatically before `dev` and `build`; run manually with `pnpm images`.
 */
import { access, mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";
import { imageSlots, type ImageSlotKey } from "@/lib/images";

const root = process.cwd();
const EXTENSIONS = ["webp", "avif", "jpg", "jpeg", "png"] as const;

export type ManifestEntry = { src: string; width: number; height: number; blurDataURL: string };

async function exists(file: string): Promise<boolean> {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

async function findFile(slot: string): Promise<string | null> {
  for (const ext of EXTENSIONS) {
    const file = path.join(root, "public", "images", `${slot}.${ext}`);
    if (await exists(file)) return file;
  }
  return null;
}

async function buildManifest() {
  const manifest: Partial<Record<ImageSlotKey, ManifestEntry>> = {};
  const found: string[] = [];

  for (const slot of Object.keys(imageSlots) as ImageSlotKey[]) {
    const file = await findFile(slot);
    if (!file) continue;
    const image = sharp(file);
    const meta = await image.metadata();
    if (!meta.width || !meta.height) throw new Error(`Cannot read size of ${file}`);
    const blur = await image.resize(16).webp({ quality: 40 }).toBuffer();
    manifest[slot] = {
      src: "/" + path.relative(path.join(root, "public"), file).split(path.sep).join("/"),
      width: meta.width,
      height: meta.height,
      blurDataURL: `data:image/webp;base64,${blur.toString("base64")}`,
    };
    found.push(slot);
  }

  const out = path.join(root, "lib", "image-manifest.json");
  const json = JSON.stringify(manifest, null, 2) + "\n";
  const previous = (await exists(out)) ? await readFile(out, "utf8") : "";
  if (previous !== json) await writeFile(out, json);
  return found;
}

async function writeBrief(found: Set<string>) {
  const groups = new Map<string, string[]>();
  for (const [slot, def] of Object.entries(imageSlots)) {
    const page = slot.split("/")[0] ?? "other";
    const row = `| \`public/images/${slot}.webp\` | ${def.width} × ${def.height} | ${def.subject} | ${
      found.has(slot) ? "✅ supplied" : "⏳ fallback"
    } |`;
    groups.set(page, [...(groups.get(page) ?? []), row]);
  }

  const sections = [...groups.entries()].map(
    ([page, rows]) =>
      `### ${page[0]?.toUpperCase()}${page.slice(1)}\n\n| File | Size (px) | Subject | Status |\n|---|---|---|---|\n${rows.join("\n")}`,
  );

  const md = `# Image brief

_Generated by \`pnpm images\` from \`lib/images.ts\`; do not edit by hand._

Every image on the site is a named **slot**. Until a file exists, the site shows a designed
gradient/glow fallback with the same aspect ratio, so nothing looks broken and there is no layout shift.

## How to supply an image

1. Export at the size listed (or larger, same aspect ratio). **WebP, quality ~80**, sRGB.
2. Save it at the exact path in the table (AVIF, JPG or PNG with the same name also work).
3. Run \`pnpm dev\` or \`pnpm build\`: the manifest regenerates and the fallback is replaced.
4. Update the image's \`alt\` text in the matching \`content/pages/*.ts\` file if the subject changed.

## Art direction

- Palette: deep navy (#06162e) with electric blue (#0879f9) and cyan (#08cfe3) light. Avoid warm casts,
  except for sunrise accents on the Home hero and the About band.
- Hero images (\`*/hero\`): keep the **left ~45% dark and uncluttered**; text sits there on desktop.
  On mobile, images are cropped to the centre-right, so keep the subject between 55% and 80% of the width.
- Card images: subject centred, no text in the image.
- People: diverse, professional, natural poses; no recognisable logos other than XBPL's.
- Mockup images are AI-generated placeholders. Replace them with licensed photography or newly generated
  images you hold rights to.

${sections.join("\n\n")}
`;
  await mkdir(path.join(root, "docs"), { recursive: true });
  await writeFile(path.join(root, "docs", "IMAGE_BRIEF.md"), md);
}

async function main() {
  const found = await buildManifest();
  await writeBrief(new Set(found));
  const total = Object.keys(imageSlots).length;
  console.log(`Image manifest: ${found.length}/${total} slots supplied.`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
